Docs: fix the example for "Using an Existing Schema" (#1761)
* Fix the example for "Using an Existing Schema"

The file caused the following error:
```
const gql = String.raw;
      ^
SyntaxError: Identifier 'gql' has already been declared
```

* Update migration-two-dot.md

* Update migration-two-dot.md